---
title: "Upper digestive tract"
author: "Ludvig Larsson"
date: "2/11/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(STutility)
```

Collect spaceranger output files

```{r}

samples <- list.files(path = "~/Oral/data", pattern = "filtered_feature_bc_matrix.h5", full.names = TRUE, recursive = TRUE)
imgs <- list.files(path = "~/Oral/data", pattern = "tissue_hires_image.png", full.names = TRUE, recursive = TRUE)
spotfiles <- list.files(path = "~/Oral/data", pattern = "tissue_positions_list_curated.csv", full.names = TRUE, recursive = TRUE)
json <- list.files(path = "~//Oral/data", pattern = "scalefactors_json.json", full.names = TRUE, recursive = TRUE)

infoTable <- data.frame(samples, imgs, spotfiles, json, section_id = paste0("section_", 1:4),
                        type = c("VAD", "VAD", "VAC", "VAC"),
                        day = c( "d0", "d14", "d0", "d14"))
infoTable

```

Create Seurat object

```{r}
se.Oral <- InputFromTable(infoTable)
```

```{r eval=FALSE, include=FALSE}

se.Oral <- LoadImages(se.Oral, time.resolve = FALSE)
se.Oral <- ManualAnnotation(se.Oral)
se.Oral <- SubsetSTData(se.Oral, expression = labels %in% "Default")

# Export new selections
for (i in seq_along(spotfiles)) {
  f <- spotfiles[i]
  newf <- gsub(pattern = "\\.csv", replacement = "_curated.csv", x = f)
  alignment <- read.table(f, sep = ",")
  cat(sprintf("Number of spots selected before filtering: %s", sum(alignment$V2)), "\n")
  rownames(alignment) <- paste0(alignment$V1, "_", i)
  alignment$V2 <- ifelse(rownames(alignment) %in% colnames(se.Oral), 1, 0)
  cat(sprintf("Number of spots selected after filtering: %s", sum(alignment$V2)), "\n")
  write.table(alignment, file = newf, quote = F, row.names = F, col.names = F, sep = ",")
}

```

# Date
***

```{r}
date()
```

# Session
***

```{r}
devtools::session_info()
```


